use_frameworks!

target 'FreestylerCore_Example' do
  pod 'FreestylerCore', :path => '../'

  target 'FreestylerCore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
